version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app 
    volumes:
      - ./services/web/project/static:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.web
      
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/web/project/static:/home/app/web/project/static
    ports:
      - 1337:80
    depends_on:
      - web

